name: fund-crawler
on: [push]
env:
  TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  build:
    name: crawler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run start # will run `yarn run start` command
